# Generated by Django 4.2.8 on 2023-12-13 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter bot name', max_length=80, unique=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intentname', models.CharField(help_text='Enter Intent name', max_length=100, unique=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml.bot')),
            ],
            options={
                'ordering': ['-intentname'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsename', models.CharField(help_text='Enter Response name', max_length=100, unique=True)),
                ('content', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml.bot')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml.intent')),
            ],
            options={
                'ordering': ['-responsename'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storyname', models.CharField(help_text='Enter Story name', max_length=100, unique=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml.bot')),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml.intent')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaml.response')),
            ],
            options={
                'ordering': ['-storyname'],
            },
        ),
    ]
