# Generated by Django 4.2.8 on 2023-12-13 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yaml', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intent',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='intent',
            old_name='intentname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='responsename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='storyname',
            new_name='name',
        ),
    ]
